---
functional:
  - Возможность просмотра на русском или английском языке
  - Возможность авторизации через Github
  - Возможность авторизации по email и паролю
  - Возможность восстановить пароль
  - Нельзя повторно зарегистрироваться по одному email
  - Нельзя зарегистрироваться по несуществующему email
  - Реализована возможность редактировать профиль
  - Реализована возможность сменить пароль 
  - Пользователь может писать код на Javascript в редакторе
  - Редактор проверяет и выдает корректный результат проверки написанного кода
  - Редактор реагирует и выдает сообщение, если пользователь написал некорректный код 
  - Редактор корректно реагирует на синтаксис, отображая готовые шаблоны
  - Редактор корректно определяет элементы кода
  - В редакторе реализованы основные горячие клавиши для работы с кодом
  - Неавторизованный пользователь может запускать редактор
  - Пользователь может сохранить сниппет
  - Пользователь может дать наименование сниппету 
  - Пользователь может переименовать сниппет
  - Пользователь может удалить сохраненный сниппет
  - Пользователь может редактировать сохраненный сниппет
  - Пользователь может делиться ссылкой на сниппет
  - Пользователь может скопировать свой код для применения на других сайтах
  - Возможность просматривать сниппеты, выложенные другими пользователями
  - Возможность ограничить просмотр сниппета другими пользователями
  - Возможность ограничить или предоставить доступ к редактированию сниппета другим пользователям 
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь удобную мобильную версию
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен обладать удобной, интуитивно понятной и быстрой регистрацией 
  - Сайт должен быть совместим с последними версиями распространенных браузеров
implicit:
  - На сайте реализована обратная связь с поддержкой 
  - На сайте реализован туториал
  - Сайт предоставляет информацию об условиях использования материалов и услуг
  - На сайте есть возможность добавлять и менять аватар профиля
